gru_type: AUGRU
alpha: 1.0
att_hidden_units: [64, 16]
att_activation: relu
att_weight_normalization: True
l2_reg_dnn: 0
l2_reg_embedding: 1.0e-6
dnn_dropout: 0.2
init_std: 0.0001
use_bn: True
use_negsampling: False
gpus: null